import json
from bs4 import BeautifulSoup

def parse_wsj_headlines(html_content):
    """
    Parses the given WSJ-style HTML content and extracts article data
    into the specified JSON format.
    """
    soup = BeautifulSoup(f"<div>{html_content}</div>", "html.parser")
    articles_data = []
    
    SOURCE_NAME = "The Wall Street Journal"
    SOURCE_ID = "the-wall-street-journal" 

    article_blocks = soup.select('div.eyw533s0')

    for block in article_blocks:
        
        title_link = block.select_one('h3 a[data-testid="flexcard-headline"]')
        
        if not title_link:
            continue
            
        url = title_link.get('href')
        
        title_text_div = title_link.select_one('div.css-w05dlz-HeadlineTextBlock')
        title = title_text_div.get_text(strip=True) if title_text_div else "Unknown Title"

        authors = []
        author_spans = block.select('div[data-testid="byline"] a.epvx9353 span.css-1wc2zh5, div[data-testid="byline"] p.epvx9352:not(.css-1s90smj-AuthorPlaintext)')
        
        for span in author_spans:
            authors.append(span.get_text(strip=True))

        plain_authors = block.select('div[data-testid="byline"] p.epvx9352.css-1s90smj-AuthorPlaintext')
        
        if not authors:
             for pa in plain_authors:
                text = pa.get_text(strip=True)
                if text and text != "By":
                    authors.append(text)
        
        author_string = ", ".join(authors) if authors else None

        time_tag = block.select_one('p[data-testid="timestamp-text"]')
        published_at = time_tag.get_text(strip=True) if time_tag else None

    
        description_tag = block.find_next_sibling('p', class_='css-1fy19we')
        description = description_tag.get_text(strip=True) if description_tag else "No summary available in snippet. (Could be video or online-only content)"

        articles_data.append({
            "source": {
                "id": SOURCE_ID,
                "name": SOURCE_NAME
            },
            "author": author_string, 
            "title": title,
            "description": description,
            "url": url,
            "urlToImage": None,
            "publishedAt": published_at,
            "content": None 
        })
    
    output_filename = "parsed_wsj_articles.json"
    with open(output_filename, "w", encoding="utf-8") as f:
        json.dump({"articles": articles_data}, f, indent=2)
    
    print(f"Successfully parsed and saved {len(articles_data)} articles to {output_filename}")
    
    return articles_data

def main():
    WSJ_SNIPPET = """
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><div class="css-1es9ut9"><div data-testid="content-tag" class="e17r9aji1 css-7d8lo8-FlagContainer"><span class="css-zk5dh1">Opinion</span></div></div></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/opinion/is-a-mayor-mamdani-a-blessing-in-disguise-socialism-new-york-7903db43?mod=Searchresults&amp;pos=1&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">Is a Mayor Mamdani a Blessing in Disguise?</div></a></h3><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">July 8, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Jul 9, 2025<!-- -->, print edition as '<!-- -->Is a Mayor Mamdani a Blessing in Disguise?<!-- -->'</p></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><nav class="breadcrumb css-q8t0wg-NavWrapper ed3psuc7" aria-label="New York flashline"><ol class="css-1noupi4-List ed3psuc3"><li class="css-1uhzxw8-ListItem ed3psuc2"><div class="css-17x5lw"><p data-testid="flashline" class="em6l15r0 css-118tfk7-withBrowserDarkMode">New York</p></div></li></ol></nav></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/us-news/the-mamdani-millionaires-supporting-the-socialist-for-nyc-mayor-13c1636b?mod=Searchresults&amp;pos=2&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">The Mamdani Millionaires Supporting the Socialist for NYC Mayor</div></a></h3><div class="e1sf124z13 css-taoc2f-FullBlock"><div class="eh42cdm6 css-4nm965-AuthoringContainer"><div class="css-1th2wme"><div class="eh42cdm5 css-5h3nb1-AuthoringContent"><div class="css-10mmni2"><div class="css-11k10ko"><div data-testid="byline" class="epvx9354 css-5gcfbw-BylineContainer"> <p class="epvx9352 css-1s90smj-AuthorPlaintext">By </p><a data-testid="author-link" href="https://www.wsj.com/news/author/9840" target="_self" aria-label="Author page for Kevin T. Dugan" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">Kevin T. Dugan</span></span></a></div></div></div></div></div></div></div><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">July 6, 2025</p></div></div></div></div></div></div></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><div class="css-1es9ut9"><div data-testid="content-tag" class="e17r9aji1 css-7d8lo8-FlagContainer"><span class="css-zk5dh1">Opinion</span></div></div></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/opinion/mamdani-and-the-lefts-alliance-with-radical-islam-new-york-mayor-658b68ad?mod=Searchresults&amp;pos=3&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">Mamdani and the Left’s Alliance With Radical Islam</div></a></h3><div class="e1sf124z13 css-taoc2f-FullBlock"><div class="eh42cdm6 css-4nm965-AuthoringContainer"><div class="css-1th2wme"><div class="eh42cdm5 css-5h3nb1-AuthoringContent"><div class="css-10mmni2"><div class="css-11k10ko"><div data-testid="byline" class="epvx9354 css-5gcfbw-BylineContainer"> <p class="epvx9352 css-1s90smj-AuthorPlaintext">By </p><a data-testid="author-link" href="https://www.wsj.com/news/author/6210" target="_self" aria-label="Author page for Sadanand Dhume" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">Sadanand Dhume</span></span></a></div></div></div></div></div></div></div><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">July 16, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Jul 17, 2025<!-- -->, print edition as '<!-- -->Mamdani and the Left’s Alliance With Radical Islam<!-- -->'</p></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><nav class="breadcrumb css-q8t0wg-NavWrapper ed3psuc7" aria-label="VIDEO flashline"><ol class="css-1noupi4-List ed3psuc3"><li class="css-1uhzxw8-ListItem ed3psuc2"><div class="css-17x5lw"><p data-testid="flashline" class="em6l15r0 css-118tfk7-withBrowserDarkMode">VIDEO</p></div></li></ol></nav></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/video/mamdani-delivers-upset-in-new-york-mayoral-primary/66C230AF-E7B6-4350-81E3-B51EE98AAA39?mod=Searchresults&amp;pos=4&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">Mamdani Delivers Upset in New York Mayoral Primary</div></a></h3><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">June 25, 2025</p></div></div></div></div></div></div></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><div class="css-1es9ut9"><div data-testid="content-tag" class="e17r9aji1 css-7d8lo8-FlagContainer"><span class="css-zk5dh1">Opinion</span></div></div></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/opinion/notable-quotable-mamdani-and-shoplifting-2224163c?mod=Searchresults&amp;pos=5&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">Notable &amp; Quotable: Mamdani and Shoplifting</div></a></h3><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">July 10, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Jul 11, 2025<!-- -->, print edition as '<!-- -->Notable &amp; Quotable: Mamdani and Shoplifting<!-- -->'</p></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><div class="css-1es9ut9"><div data-testid="content-tag" class="e17r9aji1 css-7d8lo8-FlagContainer"><span class="css-zk5dh1">Opinion</span></div></div></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/opinion/prof-mamdanis-curriculum-columbia-radical-918e5d04?mod=Searchresults&amp;pos=6&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">Prof. Mamdani’s Curriculum</div></a></h3><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">October 19, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Oct 20, 2025<!-- -->, print edition as '<!-- -->Prof. Mamdani’s Curriculum<!-- -->'</p></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><div class="css-1es9ut9"><div data-testid="content-tag" class="e17r9aji1 css-7d8lo8-FlagContainer"><span class="css-zk5dh1">Opinion</span></div></div></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/opinion/a-makeover-for-the-anti-mamdani-campaign-cuomo-rufo-election-93a09f33?mod=Searchresults&amp;pos=7&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">A Makeover for the Anti-Mamdani Campaign</div></a></h3><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">October 23, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Oct 24, 2025<!-- -->, print edition as '<!-- -->A Makeover for the Anti-Mamdani Campaign<!-- -->'</p></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><nav class="breadcrumb css-q8t0wg-NavWrapper ed3psuc7" aria-label="Politics flashline"><ol class="css-1noupi4-List ed3psuc3"><li class="css-1uhzxw8-ListItem ed3psuc2"><div class="css-17x5lw"><p data-testid="flashline" class="em6l15r0 css-118tfk7-withBrowserDarkMode">Politics</p></div></li></ol></nav></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/us-news/new-york-officials-to-team-up-with-wall-street-to-keep-national-guard-out-a3e391c9?mod=Searchresults&amp;pos=8&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">New York Officials to Team Up With Wall Street to Keep National Guard Out</div></a></h3><div class="e1sf124z13 css-taoc2f-FullBlock"><div class="eh42cdm6 css-4nm965-AuthoringContainer"><div class="css-1th2wme"><div class="eh42cdm5 css-5h3nb1-AuthoringContent"><div class="css-10mmni2"><div class="css-11k10ko"><div data-testid="byline" class="epvx9354 css-5gcfbw-BylineContainer"> <p class="epvx9352 css-1s90smj-AuthorPlaintext">By </p><a data-testid="author-link" href="https://www.wsj.com/news/author/9092" target="_self" aria-label="Author page for James Fanelli" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">James Fanelli</span></span></a><p class="epvx9352 css-1s90smj-AuthorPlaintext">, </p><a data-testid="author-link" href="https://www.wsj.com/news/author/9864" target="_self" aria-label="Author page for Jack Morphet" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">Jack Morphet</span></span></a><p class="epvx9352 css-1s90smj-AuthorPlaintext"> and </p><a data-testid="author-link" href="https://www.wsj.com/news/author/7346" target="_self" aria-label="Author page for Corrie Driebusch" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">Corrie Driebusch</span></span></a></div></div></div></div></div></div></div><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">November 17, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Nov 18, 2025<!-- -->, print edition as '<!-- -->New York Works to Fend Off A Trump Troop Deployment<!-- -->'</p></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><nav class="breadcrumb css-q8t0wg-NavWrapper ed3psuc7" aria-label="Politics flashline"><ol class="css-1noupi4-List ed3psuc3"><li class="css-1uhzxw8-ListItem ed3psuc2"><div class="css-17x5lw"><p data-testid="flashline" class="em6l15r0 css-118tfk7-withBrowserDarkMode">Politics</p></div></li></ol></nav></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/politics/elections/nyc-mayor-democratic-primary-preliminary-results-5fac0c90?mod=Searchresults&amp;pos=9&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">Mamdani Declares Victory in NYC Mayoral Primary as Cuomo Concedes</div></a></h3><div class="e1sf124z13 css-taoc2f-FullBlock"><div class="eh42cdm6 css-4nm965-AuthoringContainer"><div class="css-1th2wme"><div class="eh42cdm5 css-5h3nb1-AuthoringContent"><div class="css-10mmni2"><div class="css-11k10ko"><div data-testid="byline" class="epvx9354 css-5gcfbw-BylineContainer"> <p class="epvx9352 css-1s90smj-AuthorPlaintext">By </p><a data-testid="author-link" href="https://www.wsj.com/news/author/9219" target="_self" aria-label="Author page for Alyssa Lukpat" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">Alyssa Lukpat</span></span></a><p class="epvx9352 css-1s90smj-AuthorPlaintext">, </p><a data-testid="author-link" href="https://www.wsj.com/news/author/9483" target="_self" aria-label="Author page for Victoria Albert" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">Victoria Albert</span></span></a><p class="epvx9352 css-1s90smj-AuthorPlaintext"> and </p><a data-testid="author-link" href="https://www.wsj.com/news/author/9821" target="_self" aria-label="Author page for Jasmine Li" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">Jasmine Li</span></span></a></div></div></div></div></div></div></div><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">June 25, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Jun 25, 2025<!-- -->, print edition as '<!-- -->Cuomo Concedes Mayoral Primary to Mamdani<!-- -->'</p></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><div class="css-1es9ut9"><div data-testid="content-tag" class="e17r9aji1 css-7d8lo8-FlagContainer"><span class="css-zk5dh1">Opinion</span></div></div></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/opinion/living-in-zohran-mamdanis-america-44ea8b90?mod=Searchresults&amp;pos=10&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">Living in Zohran Mamdani’s America</div></a></h3><div class="e1sf124z13 css-taoc2f-FullBlock"><div class="eh42cdm6 css-4nm965-AuthoringContainer"><div class="css-1th2wme"><div class="eh42cdm5 css-5h3nb1-AuthoringContent"><div class="css-10mmni2"><div class="css-11k10ko"><div data-testid="byline" class="epvx9354 css-5gcfbw-BylineContainer"> <p class="epvx9352 css-1s90smj-AuthorPlaintext">By WSJ Opinion Staff </p></div></div></div></div></div></div></div><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">August 8, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Aug 9, 2025<!-- -->, print edition as '<!-- -->Living in Zohran Mamdani’s America<!-- -->'</p></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><div class="css-1es9ut9"><div data-testid="content-tag" class="e17r9aji1 css-7d8lo8-FlagContainer"><span class="css-zk5dh1">Opinion</span></div></div></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/opinion/when-will-ai-elect-a-president-4792d31f?mod=Searchresults&amp;pos=11&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">When Will AI Elect a President?</div></a></h3><div class="e1sf124z13 css-taoc2f-FullBlock"><div class="eh42cdm6 css-4nm965-AuthoringContainer"><div class="css-1th2wme"><div class="eh42cdm5 css-5h3nb1-AuthoringContent"><div class="css-10mmni2"><div class="css-11k10ko"><div data-testid="byline" class="epvx9354 css-5gcfbw-BylineContainer"> <p class="epvx9352 css-1s90smj-AuthorPlaintext">By </p><a data-testid="author-link" href="https://www.wsj.com/news/author/8679" target="_self" aria-label="Author page for Andy Kessler" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">Andy Kessler</span></span></a></div></div></div></div></div></div></div><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">November 16, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Nov 17, 2025<!-- -->, print edition as '<!-- -->When Will AI Elect a President?<!-- -->'</p></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><nav class="breadcrumb css-q8t0wg-NavWrapper ed3psuc7" aria-label="PODCAST flashline"><ol class="css-1noupi4-List ed3psuc3"><li class="css-1uhzxw8-ListItem ed3psuc2"><div class="css-17x5lw"><p data-testid="flashline" class="em6l15r0 css-118tfk7-withBrowserDarkMode">PODCAST</p></div></li></ol></nav></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/podcasts/opinion-free-expression/democrats-make-a-startling-comeback-on-election-day/C523EBD0-3D15-4C82-A292-25FC6696353A?mod=Searchresults&amp;pos=12&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">Democrats Make a Startling Comeback on Election Day </div></a></h3><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">November 5, 2025</p></div></div></div></div></div></div></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><nav class="breadcrumb css-q8t0wg-NavWrapper ed3psuc7" aria-label="Essay flashline"><ol class="css-1noupi4-List ed3psuc3"><li class="css-1uhzxw8-ListItem ed3psuc2"><div class="css-17x5lw"><p data-testid="flashline" class="em6l15r0 css-118tfk7-withBrowserDarkMode">Essay</p></div></li></ol></nav></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/politics/elections/downwardly-mobile-elites-love-zohran-mamdani-37729120?mod=Searchresults&amp;pos=13&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">Downwardly Mobile Elites Love Zohran Mamdani</div></a></h3><div class="e1sf124z13 css-taoc2f-FullBlock"><div class="eh42cdm6 css-4nm965-AuthoringContainer"><div class="css-1th2wme"><div class="eh42cdm5 css-5h3nb1-AuthoringContent"><div class="css-10mmni2"><div class="css-11k10ko"><div data-testid="byline" class="epvx9354 css-5gcfbw-BylineContainer"> <p class="epvx9352 css-1s90smj-AuthorPlaintext">By </p><p class="epvx9352 css-1s90smj-AuthorPlaintext">Reihan Salam</p></div></div></div></div></div></div></div><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">July 24, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Jul 26, 2025<!-- -->, print edition as '<!-- -->Downwardly Mobile Elites Love Zohran Mamdani Why Urban Millennials Love Mamdani<!-- -->'</p></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><div class="css-1es9ut9"><div data-testid="content-tag" class="e17r9aji1 css-7d8lo8-FlagContainer"><span class="css-zk5dh1">Opinion</span></div></div></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/opinion/i-want-your-vote-you-bigot-84cd61ac?mod=Searchresults&amp;pos=14&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">I Want Your Vote, You Bigot</div></a></h3><div class="e1sf124z13 css-taoc2f-FullBlock"><div class="eh42cdm6 css-4nm965-AuthoringContainer"><div class="css-1th2wme"><div class="eh42cdm5 css-5h3nb1-AuthoringContent"><div class="css-10mmni2"><div class="css-11k10ko"><div data-testid="byline" class="epvx9354 css-5gcfbw-BylineContainer"> <p class="epvx9352 css-1s90smj-AuthorPlaintext">By </p><a data-testid="author-link" href="https://www.wsj.com/news/author/5686" target="_self" aria-label="Author page for Karl Rove" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">Karl Rove</span></span></a></div></div></div></div></div></div></div><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">October 29, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Oct 30, 2025<!-- -->, print edition as '<!-- -->I Want Your Vote, You Bigot<!-- -->'</p></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><div class="css-1es9ut9"><div data-testid="content-tag" class="e17r9aji1 css-7d8lo8-FlagContainer"><span class="css-zk5dh1">Opinion</span></div></div></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/opinion/dont-forget-david-dinkins-zohran-mamdani-new-york-f3dd3df4?mod=Searchresults&amp;pos=15&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">Don’t Forget David Dinkins</div></a></h3><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">November 12, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Nov 13, 2025<!-- -->, print edition as '<!-- -->Don’t Forget David Dinkins<!-- -->'</p></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><div class="css-1es9ut9"><div data-testid="content-tag" class="e17r9aji1 css-7d8lo8-FlagContainer"><span class="css-zk5dh1">Opinion</span></div></div></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/opinion/zohran-mamdani-democratic-party-socialists-new-york-city-mayor-25351711?mod=Searchresults&amp;pos=16&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">Zohran Mamdani and the Democrats</div></a></h3><div class="e1sf124z13 css-taoc2f-FullBlock"><div class="eh42cdm6 css-4nm965-AuthoringContainer"><div class="css-1th2wme"><div class="eh42cdm5 css-5h3nb1-AuthoringContent"><div class="css-10mmni2"><div class="css-11k10ko"><div data-testid="byline" class="epvx9354 css-5gcfbw-BylineContainer"> <p class="epvx9352 css-1s90smj-AuthorPlaintext">By </p><a data-testid="author-link" href="https://www.wsj.com/news/author/8695" target="_self" aria-label="Author page for The Editorial Board" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">The Editorial Board</span></span></a></div></div></div></div></div></div></div><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">October 20, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Oct 21, 2025<!-- -->, print edition as '<!-- -->Mamdani and the Democrats<!-- -->'</p></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><div class="css-1es9ut9"><div data-testid="content-tag" class="e17r9aji1 css-7d8lo8-FlagContainer"><span class="css-zk5dh1">Opinion</span></div></div></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/opinion/democrats-fall-into-the-mamdani-line-3044eb70?mod=Searchresults&amp;pos=17&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">Democrats Fall Into the Mamdani Line</div></a></h3><div class="e1sf124z13 css-taoc2f-FullBlock"><div class="eh42cdm6 css-4nm965-AuthoringContainer"><div class="css-1th2wme"><div class="eh42cdm5 css-5h3nb1-AuthoringContent"><div class="css-10mmni2"><div class="css-11k10ko"><div data-testid="byline" class="epvx9354 css-5gcfbw-BylineContainer"> <p class="epvx9352 css-1s90smj-AuthorPlaintext">By </p><a data-testid="author-link" href="https://www.wsj.com/news/author/8695" target="_self" aria-label="Author page for The Editorial Board" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">The Editorial Board</span></span></a></div></div></div></div></div></div></div><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">October 27, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Oct 27, 2025<!-- -->, print edition as '<!-- -->Democrats Fall Into the Mamdani Line<!-- -->'</p></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><div class="css-1es9ut9"><div data-testid="content-tag" class="e17r9aji1 css-7d8lo8-FlagContainer"><span class="css-zk5dh1">Opinion</span></div></div></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/opinion/new-york-city-zohran-mamdani-taxes-business-bill-lee-tennessee-83d6374d?mod=Searchresults&amp;pos=18&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">The Bidding War for New York Refugees</div></a></h3><div class="e1sf124z13 css-taoc2f-FullBlock"><div class="eh42cdm6 css-4nm965-AuthoringContainer"><div class="css-1th2wme"><div class="eh42cdm5 css-5h3nb1-AuthoringContent"><div class="css-10mmni2"><div class="css-11k10ko"><div data-testid="byline" class="epvx9354 css-5gcfbw-BylineContainer"> <p class="epvx9352 css-1s90smj-AuthorPlaintext">By </p><a data-testid="author-link" href="https://www.wsj.com/news/author/8695" target="_self" aria-label="Author page for The Editorial Board" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">The Editorial Board</span></span></a></div></div></div></div></div></div></div><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">November 10, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Nov 11, 2025<!-- -->, print edition as '<!-- -->The Bidding War for New York Refugees<!-- -->'</p></div>
<div class="eyw533s0 css-tya87"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><div class="css-1es9ut9"><div data-testid="content-tag" class="e17r9aji1 css-7d8lo8-FlagContainer"><span class="css-zk5dh1">Opinion</span></div></div></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/opinion/elise-stefanik-aims-for-the-new-york-governors-office-cc429b06?mod=Searchresults&amp;pos=19&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">Elise Stefanik Aims for the New York Governor’s Office</div></a></h3><div class="e1sf124z13 css-taoc2f-FullBlock"><div class="eh42cdm6 css-4nm965-AuthoringContainer"><div class="css-1th2wme"><div class="eh42cdm5 css-5h3nb1-AuthoringContent"><div class="css-10mmni2"><div class="css-11k10ko"><div data-testid="byline" class="epvx9354 css-5gcfbw-BylineContainer"> <p class="epvx9352 css-1s90smj-AuthorPlaintext">By </p><a data-testid="author-link" href="https://www.wsj.com/news/author/5470" target="_self" aria-label="Author page for William McGurn" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">William McGurn</span></span></a></div></div></div></div></div></div></div><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">November 10, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Nov 11, 2025<!-- -->, print edition as '<!-- -->Elise Stefanik Aims for Albany<!-- -->'</p></div>
<div class="eyw533s0 css-1azheiz"><div style="display: contents;"><div class="e1sf124z9 css-xgdeql-StyledStack"><div class="e1sf124z0 css-1v7l3df-TopSpaceRemover"></div><div class="e1sf124z14 css-cjqys3-FlashlineWrapper"><nav class="breadcrumb css-q8t0wg-NavWrapper ed3psuc7" aria-label="Real Estate flashline"><ol class="css-1noupi4-List ed3psuc3"><li class="css-1uhzxw8-ListItem ed3psuc2"><div class="css-17x5lw"><p data-testid="flashline" class="em6l15r0 css-118tfk7-withBrowserDarkMode">Real Estate</p></div></li></ol></nav></div><h3 class="css-fsvegl"><a data-fclink="" text-decoration="none" href="https://www.wsj.com/real-estate/nyc-real-estate-zohran-mamdani-4797e4c9?mod=Searchresults&amp;pos=20&amp;page=3" data-testid="flexcard-headline" target="_self" class="e1sf124z12 css-18pi1z0-CardLink"><div class="e1sf124z8 css-w05dlz-HeadlineTextBlock">NYC Developers Gripped by Hysteria After Mamdani’s Sudden Rise</div></a></h3><div class="e1sf124z13 css-taoc2f-FullBlock"><div class="eh42cdm6 css-4nm965-AuthoringContainer"><div class="css-1th2wme"><div class="eh42cdm5 css-5h3nb1-AuthoringContent"><div class="css-10mmni2"><div class="css-11k10ko"><div data-testid="byline" class="epvx9354 css-5gcfbw-BylineContainer"> <p class="epvx9352 css-1s90smj-AuthorPlaintext">By </p><a data-testid="author-link" href="https://www.wsj.com/news/author/9250" target="_self" aria-label="Author page for Rebecca Picciotto" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">Rebecca Picciotto</span></span></a><p class="epvx9352 css-1s90smj-AuthorPlaintext"> and </p><a data-testid="author-link" href="https://www.wsj.com/news/author/8932" target="_self" aria-label="Author page for Peter Grant" class="epvx9353 css-jv4qg1-AuthorLink"><span class="css-17x5lw"><span class="css-1wc2zh5">Peter Grant</span></span></a></div></div></div></div></div></div></div><div class="e1sf124z6 css-10kw0xk-SupportingMenuBlock"><div class="css-1sxukgb"><div class="css-fcx7ij"><div class="css-nr8oy5"><p data-testid="timestamp-text" class="es486sg1 css-1ubj98l-TimeTag">June 26, 2025</p></div></div></div></div></div></div><p class="css-1fy19we">Appeared in the <!-- -->Jul 2, 2025<!-- -->, print edition as '<!-- -->Developers Worry Over NYC Candidate<!-- -->'</p></div>"""
    
    parse_wsj_headlines(WSJ_SNIPPET)

if __name__ == "__main__":
    main()